version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.13.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Verify AWS CLI Installation
          command: aws --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build --prod

      - run:
          name: Build Docker Image
          command: docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:1.0 .

      - run:
          name: Docker Login to AWS ECR
          command: |
            aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

      - run:
          name: Push Docker Image
          command: docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:1.0
